---
work:
- name: katiemcgarry
  title: Katie McGarry (2011)
  color: "#edc667"
  url-title: katiemcgarrymusic.com
  url: http://katiemcgarrymusic.com
  meta:
  - Drupal
  - Layout&nbsp;design
  - Site&nbsp;building
  - Theming
  - Custom&nbsp;development
  images:
  - kmg-logo.png
  - kmg-front.png
  - kmg-music.png
  - kmg-bio.png
- name: merchantmanpub
  title: The Merchantman Pub (2010)
  color: "#053714"
  meta:
  - Drupal
  - Layout&nbsp;design
  - Site&nbsp;building
  - Theming
  images:
  - mmp-logo.png
  - mmp-front.png
  - mmp-footer.png
  - mmp-newsletter-front.png
  - mmp-newsletter.png
  - mmp-menu.png
  - mmp-pictures.png
- name: miekewillems
  title: Mieke Willems (2009)
  color: "#111a9d"
  meta:
  - Drupal
  - Layout&nbsp;design
  - Site&nbsp;building
  - Theming
  - Ecommerce
  - Static&nbsp;to&nbsp;dynamic
  images:
  - mw-logo.png
  - mw-front.png
  - mw-categories.png
  - mw-shop.png
  - mw-product.png
twitter:
  username: dannyjoris
disqus:
  id: dannyjoris
google_analytics:
  account: UA-8738645-5
email: mail@dannyjoris.ca
author: Danny Joris
title: Danny Joris
domain: dannyjoris.ca
kramdown:
  auto_ids: true
  footnote_nr: '1'
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_number_start: '1'
    coderay_tab_width: '4'
    coderay_bold_every: '10'
    coderay_css: style
timezone: ''
permalink: "/blog/:year/:month/:day/:title"
port: 4000
show_drafts: ''
exclude:
- vendor
- vendor
- vendor
- vendor
collections:
  posts:
    output: true
    permalink: "/blog/:year/:month/:day/:title"
