permalink: /blog/:year/:month/:day/:title
destination: ./__site

# Configuration
# configuration required for some pages
domain: dannyjoris.ca
title: Danny Joris
author: Danny Joris
email: mail@dannyjoris.ca

google_analytics:
  account: UA-8738645-5

disqus:
  id: dannyjoris

twitter:
  username: dannyjoris

#  Work
#  Images need to be placed in /images/work/
#  array structure: http://stackoverflow.com/a/8869290
#
#  machinename:
#    title: Human name
#    description: "This is an optional description."
#    color: #ff0000
#    url-title: example.com
#    url: http://example.com
#    meta:
#      - Drupal
#      - Layout&nbsp;design
#      - Site&nbsp;building
#      - Theming
#      - Custom&nbsp;development
#    images:
#      - image1.png
#      - image2.png
#      - image3.png
work:
  - name: katiemcgarry
    title: Katie McGarry (2011)
    color: "#edc667"
    url-title: katiemcgarrymusic.com
    url: http://katiemcgarrymusic.com
    meta:
      - Drupal
      - Layout&nbsp;design
      - Site&nbsp;building
      - Theming
      - Custom&nbsp;development
    images:
      - kmg-logo.png
      - kmg-front.png
      - kmg-music.png
      - kmg-bio.png
  - name: merchantmanpub
    title: The Merchantman Pub (2010)
    color: "#053714"
    meta:
      - Drupal
      - Layout&nbsp;design
      - Site&nbsp;building
      - Theming
    images:
      - mmp-logo.png
      - mmp-front.png
      - mmp-footer.png
      - mmp-newsletter-front.png
      - mmp-newsletter.png
      - mmp-menu.png
      - mmp-pictures.png
  - name: miekewillems
    title: Mieke Willems (2009)
    color: "#111a9d"
    meta:
      - Drupal
      - Layout&nbsp;design
      - Site&nbsp;building
      - Theming
      - Ecommerce
      - Static&nbsp;to&nbsp;dynamic
    images:
      - mw-logo.png
      - mw-front.png
      - mw-categories.png
      - mw-shop.png
      - mw-product.png
